spring:
  rabbitmq:
    host: localhost # rabbitmq的连接地址
    port: 5672 # rabbitmq的连接端口号
    virtual-host: /mall # rabbitmq的虚拟host,在管理界面配置 /mall
    username: mall # rabbitmq的用户名,创建用户
    password: mall # rabbitmq的密码
    publisher-confirms: true #消息发送到交换器确认:如果对异步消息需要回调必须设置为true
    publisher-returns: true #消息发送到队列确认

#死信队列
#用于解决用户下单以后，订单超时如何取消订单的问题。
#
#用户进行下单操作（会有锁定商品库存、使用优惠券、积分一系列的操作）；
#生成订单，获取订单的id；
#获取到设置的订单超时时间（假设设置的为60分钟不支付取消订单）；
#按订单超时时间发送一个延迟消息给RabbitMQ，让它在订单超时后触发取消订单的操作；
#如果用户没有支付，进行取消订单操作（释放锁定商品库存、返还优惠券、返回积分一系列操作）。

#############################################
#死信队列
#死信队列是这样一个队列，如果消息发送到该队列并超过了设置的时间，就会被转发到设置好的处理超时消息的队列当中去，利用该特性可以实现延迟消息。
#
#延迟插件
#通过安装插件，自定义交换机，让交换机拥有延迟发送消息的能力，从而实现延迟消息。
#
#结论
#由于死信队列方式需要创建两个交换机（死信队列交换机+处理队列交换机）、两个队列（死信队列+处理队列），
#而延迟插件方式只需创建一个交换机和一个队列，所以后者使用起来更简单。